// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv


import path from 'node:path'
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: path.join('prisma'),
  migrations: {
    path: "prisma/migrations",
  },
});



// import "dotenv/config";
// import path from 'node:path'
// import { defineConfig, env } from "prisma/config";

// export default defineConfig({
//   schema: path.join('prisma'),
//   migrations: {
//     path: "prisma/migrations",
//   },
//   datasource: {
//     url: env("DATABASE_URL"),
//   },
// });